branches: 
  - exe-release-management
plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/github":
    - { path: "tmp/cli", label: "Debian Exe"}
