[workspace]

members = [
    "crates/axum-server",
    "crates/db",
    "crates/grpc-api",
    "crates/cli",
]

# Don't add debug information and give us quicker incremental builds
[profile.dev]
debug = false
