version: '3.4'
services:

  # Postgres
  db:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: testpassword
      POSTGRES_USER: postgres
      POSTGRES_DB: cloak
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5


  # MailHog is an email testing tool for developers.
  smtp:
    image: mailhog/mailhog

  # Handles routing between our containers
  envoy:
    build: 
      context: .
      dockerfile: Dockerfile.envoy

  # Our external authentication micro service.
  auth:
    image: purtontech/barricade:1.0.4
    environment:
      AUTH_TYPE: encrypted
      # The following is used by the migrations and also for SQLX at compile time.
      DATABASE_URL: postgresql://postgres:testpassword@db:5432/cloak
      SECRET_KEY: 190a5bf4b3cbb6c0991967ab1c48ab30790af876720f1835cbbf3820f4f5d949
      FORWARD_URL: development
      FORWARD_PORT: 7101
      REDIRECT_URL: /app/post_registration
      SKIP_AUTH_FOR: /$$,/static/*
      ENABLE_EMAIL_OTP: 'true'

      # Send all email to mailhog
      SMTP_HOST: smtp
      SMTP_PORT: 1025
      SMTP_USERNAME: thisisnotused
      SMTP_PASSWORD: thisisnotused
      SMTP_TLS_OFF: 'true'
      RESET_DOMAIN: http://localhost:7100
      RESET_FROM_EMAIL_ADDRESS: support@wedontknowyet.com
    depends_on:
      db:
        condition: service_healthy

  development:
    build: 
      context: .
      dockerfile: Dockerfile
    
    volumes:
      - ..:/vscode:cached
      # Give access to ssh keys on the host (Is there a better way to do this?)
      - ~/.ssh:/home/host-ssh:cached
      # We need this so docker in docker works (Check this)
      - /var/run/docker.sock:/var/run/docker.sock
      - target:/vscode/target # Set target as a volume for performance. 
      - node_modules:/vscode/app/node_modules # Set target as a volume for performance. 
      - infra_node_modules:/vscode/infra/node_modules # Set target as a volume for performance. 

    environment:
      # The following is used by the migrations and also for SQLX at compile time.
      DATABASE_URL: postgresql://postgres:testpassword@db:5432/cloak
      # A less privelaged role for basic INSERTS, SELECT etc.
      APP_DATABASE_URL: postgresql://cloak:testpassword@db:5432/cloak
      VAULT_SERVER_URL: http://localhost:7103
      VAULT_SERVER_LISTEN_ADDRESS: 0.0.0.0:7103

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    working_dir: /vscode
    
    depends_on:
      - db

volumes:
  target:
  node_modules:
  infra_node_modules:
